{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "from s5v2 import *\n",
    "\n",
    "from prettytable import PrettyTable\n",
    "\n",
    "def my_table(data_sample):\n",
    "    x = PrettyTable(['Style', 'Average Price'])\n",
    "    x.add_row(['Print', pretty_average(print_ties)])\n",
    "    x.add_row(['Solid', pretty_average(solid_ties)])\n",
    "    x.add_row(['Paisley', pretty_average(paisley_ties)])\n",
    "    x.add_row(['Striped', pretty_average(striped_ties)])\n",
    "    x.add_row(['Gucci', pretty_average(gucci_ties)])\n",
    "    print(x)\n",
    "    \n",
    "def pretty_average(my_number):\n",
    "    pretty_avg = \"${:03.2f}\".format(find_average(my_average))\n",
    "    return pretty_avg\n",
    "\n",
    "#my_table()\n",
    "\n",
    "#import matplotlib.pyplot as plt\n",
    "\n",
    "def count_prices_for_brands(data_sample, brand, min_price, max_price):\n",
    "    count = 0\n",
    "    for row in data_sample:\n",
    "        if str(row[0]) == str(brand):\n",
    "            if min_price < float(row[1]) < max_price:\n",
    "                count +=1\n",
    "    return count\n",
    "\n",
    "def build_table_text(data_sample, brands):  \n",
    "    cell_text = []\n",
    "    row_text = [] \n",
    "\n",
    "#added code from video\n",
    "def build_table_text(data_sample, brands): cell_text = [] row_text = []\n",
    "unique_brand_list = sorted(set(brands))\n",
    "for brand in unique_brand_list:\n",
    "    brand = bytes.decode(brand)\n",
    "    temp_row = []\n",
    "    group1 = count_prices_for_brands(data_sample, brand, 0, 50)\n",
    "    group2 = count_prices_for_brands(data_sample, brand, 50, 100)\n",
    "    group3 = count_prices_for_brands(data_sample, brand, 100, 150)\n",
    "    group4 = count_prices_for_brands(data_sample, brand, 150, 200)\n",
    "    group5 = count_prices_for_brands(data_sample, brand, 200, 250)\n",
    "    group6 = count_prices_for_brands(data_sample, brand, 250, 10000)\n",
    "    row_list = [group1, group2, group3, group4, group5, group6]\n",
    "    temp_row.extend(row_list)\n",
    "\n",
    "    if group1 > 0:\n",
    "        if any([x >= group1 for x in row_list[1:]]):\n",
    "            cell_text.append(temp_row)\n",
    "            row_text.append(brand)\n",
    "\n",
    "return cell_text, row_text\n",
    "\n",
    "def create_table(data_sample, price_groups, brand_names, columns, exported_figure_filename):\n",
    "    tup = build_table_text(data_sample, brand_names)\n",
    "    fig = plt.figure()\n",
    "    ax = fig.add_subplot(1, 1, 1)\n",
    "\n",
    "    for group in price_groups:\n",
    "        plt.bar(group, price_groups[group]) \n",
    "    \n",
    "    if tup[0] and tup[1]:\n",
    "        ax.table(cellText=tup[0], colLabels=columns, rowLabels=tup[1], loc='bottom')\n",
    "        ax.text(-1.3, 0, 'Discounted Ties Brands', size=12, horizontalalignment='left', verticalalignment='top')\n",
    "        ax.tick_params(\n",
    "            axis='x',          # changes apply to the x-axis\n",
    "            which='both',      # both major and minor ticks are affected\n",
    "            labelbottom='off') # labels along the bottom edge are off\n",
    "\n",
    "    fig.savefig(exported_figure_filename, dpi=400, bbox_inches='tight')\n",
    "\n",
    "from collections import Counter\n",
    "def group_prices_by_range(prices_in_float):\n",
    "    \n",
    "    tally = Counter()\n",
    "\n",
    "    for item in prices_in_float:\n",
    "        bucket = 0\n",
    "        rounded_price = round(item, -1)\n",
    "        if 0 <= rounded_price <= 50:\n",
    "            bucket = 1\n",
    "        elif 50 <= rounded_price <= 100:\n",
    "            bucket = 2\n",
    "        elif 100 <= rounded_price <= 150:\n",
    "            bucket = 3\n",
    "        elif 150 <= rounded_price <= 200:\n",
    "            bucket = 4\n",
    "        elif 200 <= rounded_price <= 250:\n",
    "            bucket = 5\n",
    "        elif 250 <= rounded_price:\n",
    "            bucket = 6\n",
    "        else:\n",
    "            bucket = 7\n",
    "\n",
    "        tally[bucket] += 1\n",
    "    return tally\n",
    "\n",
    "    \n",
    "brands = my_csv['brandName']\n",
    "columns = [\"$0-50\", \"$50-100\", \"$100-150\", \"$150-200\", \"$200-250\", \"$250+\"]\n",
    "write_brand_and_price_file(\"_data/tempTableFile.csv\", data_from_csv)\n",
    "brand_and_price_data = open_with_csv(\"_data/tempTableFile.csv\", d=',')\n",
    "create_table(brand_and_price_data, price_groups, brands, columns, \"_charts/s5_prices_in_table.png\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
